apiVersion: apps/v1
kind: Deployment
metadata:
  name: seclock-deployment
  namespace: seclock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seclock
  template:
    metadata:
      labels:
        app: seclock
    spec:
      containers:
        - name: seclock
          image: 806758135252.dkr.ecr.ap-south-1.amazonaws.com/seclock:latest
          ports:
            - containerPort: 8080
